package dev.zwei.mailchimp.domain.mandrill.valueObjects

data class Message(
    val attachments: List<Any>?,
    val auto_html: Boolean?,
    val auto_text: Boolean?,
    val bcc_address: String?,
    val from_email: String?,
    val from_name: String?,
    val global_merge_vars: List<Any>?,
    val google_analytics_campaign: String?,
    val google_analytics_domains: List<Any>?,
    val headers: Headers?,
    val html: String?,
    val images: List<Any>?,
    val important: Boolean?,
    val inline_css: Boolean?,
    val merge: Boolean?,
    val merge_language: String?,
    val merge_vars: List<Any>?,
    val metadata: Metadata?,
    val preserve_recipients: Boolean?,
    val recipient_metadata: List<Any>?,
    val return_path_domain: String?,
    val signing_domain: String?,
    val subaccount: String?,
    val subject: String?,
    val tags: List<Any>?,
    val text: String?,
    val to: List<Any>?,
    val track_clicks: Boolean?,
    val track_opens: Boolean?,
    val tracking_domain: String?,
    val url_strip_qs: Boolean?,
    val view_content_link: Boolean?
)